Feature/s3019 - Tela de Comentários
MurilloIDM/cea-front-end pull request #26
Opened 2022-06-26 05:06 UTC by tcgontijo

![Untitled Project](https://user-images.githubusercontent.com/64798940/175800239-56a1ada9-7614-47c7-9f85-a08468d3a055.gif)

2022-06-26 18:36 UTC, CrisKoch approved these changes

2022-06-26 20:25 UTC, MurilloIDM requested changes

2022-06-26 20:25 UTC, MurilloIDM commented on src/components/Comments/styles.module.css
> +  /* font-weight: bolder; */
@tcgontijo remover comentário

2022-06-26 20:25 UTC, MurilloIDM commented on src/components/Layout/route.js
> +    // {
No caso dos comentários, eles não ficaram disponíveis diretamente pelo menu.

@tcgontijo remover comentário

2022-06-27 12:08 UTC, tcgontijo commented on src/components/Layout/route.js
> +    // {
Sim, eu removi porque a tela de comentários carregará a partir de uma publicação em específico. Teoricamente não terá caminho direto

2022-06-27 17:19 UTC, Gustavo780904 approved these changes

2022-06-27 22:39 UTC, MurilloIDM requested changes

2022-06-27 22:39 UTC, MurilloIDM commented on src/components/EmptyState/index.js
> +const EmptyState = ({ description = "Ops... não há dado s aqui :(" }) => {
@tcgontijo "s" ficou separado

2022-06-28 10:23 UTC, CrisKoch approved these changes

2022-06-28 10:52 UTC, MurilloIDM approved these changes

2022-06-28 10:52 UTC, merged